# This is a basic workflow to help you get started with Actions

name: pushtoshiny

# Controls when the workflow will run
on: [push]

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
    - name: Push to shiny.io
        run: |
        Rscript -e "rsconnect::setAccountInfo(name='kubsch', token='EDD281F03C9A067BF4C7F4DF216827BB', secret='QyqKFd6RyFDHQ9YvrO8QkbK7yl7VTwd16/Uwa1de')"
        Rscript -e "rsconnect::deployApp(appName = 'Confidence_Updater')" 
